language: java
jdk:
  - oraclejdk8
install: echo "skiping install phase"
script:
 - ./gradlew check jacocoTestReport
 - ./gradlew check -PenableIdeaGroovyPlugin=false
 - ./gradlew check -PideaVersion=2016.2
 - ./gradlew check -PideaVersion=2017.1.1
after_failure: ./print_surefire_reports.sh
after_success:
  - ./gradlew coveralls
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/