language: java
jdk:
  - oraclejdk8
install: echo "skiping install phase"
script: ./gradlew check -PideaDownloadSources=false
after_failure: ./print_surefire_reports.sh
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/